import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { AntdRegistry } from "@ant-design/nextjs-registry";
import { ConditionalNavbar } from "@/components";
import "./globals.css";
import { AuthProvider } from "@/contexts/AuthContext"; // 1. Import (ถูกต้องอยู่แล้ว)

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/* ✨ 2. นำ AuthProvider มาห่อหุ้มทุกอย่างที่ต้องการข้อมูลผู้ใช้ ✨ */}
        <AuthProvider>
          <AntdRegistry>
            <div className="min-h-screen bg-gray-50">
              <ConditionalNavbar />
              <main>{children}</main>
            </div>
          </AntdRegistry>
        </AuthProvider>
      </body>
    </html>
  );
}